version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    network_mode: "bridge"
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
